spring:
  application:
    name: UI
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

connector:
  orderservice:
    urlscheme:
      domain: http://localhost:8080/OrderService/
      apiversion: api/
      subdomain:
        orders: orders/
    timeouts: 30000

  timeservice:
    urlscheme:
      domain: http://localhost:8080/TimeService/
      apiversion: api/
      subdomain:
        time: time/
    timeouts: 5000